name: Node.js CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MONGODB_URL: ${{ secrets.MONGO_URL }}
      ACCESS_TOKEN: ${{ secrets.SECRET_ACCESS_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Run development build
      run: npm run dev

    - name: Run tests
      run: npm test
      env:
        MONGODB_URL: ${{ secrets.MONGO_URL }}
        ACCESS_TOKEN: ${{ secrets.SECRET_ACCESS_TOKEN }}
